spring:
  application:
    name: hr-api-gateway-spring-cloud

  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000  # Tempo em ms para conectar (2 segundos)
        response-timeout: 10s   # Tempo para obter resposta (10 segundos)
      routes:
        - id: worker_route
          uri: lb://hr-worker
          predicates:
            - Path=/hr-worker/**
          filters:
            - StripPrefix=1

        - id: payroll_route
          uri: lb://hr-payroll
          predicates:
            - Path=/hr-payroll/**
          filters:
            - StripPrefix=1

server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost